#!/bin/bash
# scripts/bb-pane-run.sh — run a command from this repository in a bb terminal
# pane, so the operator can watch it instead of reading it back afterwards.
#
# WHY THIS EXISTS: this repository's interesting steps are the host-touching ones
# — `devenv machines deploy`, a re-image, and the `scripts/*-verify.sh` suites —
# and an agent's own `terminal()` call shows the operator nothing until it is
# already over. A step the operator cannot watch is a step they have to take on
# trust, which is the opposite of what the OpenSpec changes in this repo are for.
#
# THE GENERIC TECHNIQUE LIVES ELSEWHERE: this is the repository-local copy of the
# wrapper in the `bb-terminal-pane` skill. Read that skill for the command
# surface, the pitfalls and the environment differences; the duplication here is
# deliberate, so a task in openspec/changes/ can name a repository path the way
# every other task does.
#
# MEASURED 2026-09-27 (bb host daemon, `bb` 0.x per `bb --version`):
#   * A bb terminal session is closed the instant its command exits
#     (`closeReason: "process-exit"`), so it takes the pane with it. The generated
#     wrapper therefore hands the PTY to an interactive shell at the end; without
#     that, a script that prints and returns is unreadable even though it passed.
#   * The pane does NOT inherit this shell's environment. `OP_SERVICE_ACCOUNT_TOKEN`
#     is injected into the agent's shell and is absent in the pane, and every
#     `devenv machines` invocation resolves the whole secretspec profile — so the
#     preflight and the deploys all fail there until it is exported. The wrapper
#     reads it from the 0600 file the workstation keeps it in. Presence is
#     reported; the value is never echoed, because a pane is a shared artifact.
#   * The pane also lacks `BB_THREAD_ID`/`BB_ENVIRONMENT_ID`, so the wrapper is
#     written to disk and its path is passed to `--command` rather than an inline
#     command string that the pane's shell would re-tokenize.
#   * `devenv` does NOT forward a reason flag, and secretspec.toml sets
#     `require_reason = true` — so with a manifest in the tree EVERY
#     `devenv machines …` command fails without SECRETSPEC_REASON in the
#     environment. The wrapper sets it, so a pane command behaves exactly like one
#     run by hand with the variable exported.
#
# Usage:
#   scripts/bb-pane-run.sh --title "tailnet preflight" -- ./scripts/tailnet-preflight.sh
#   scripts/bb-pane-run.sh --title "no-op deploy"      -- ./bin/devenv machines deploy netcup
set -u

TITLE=""
CMD=()

while [ $# -gt 0 ]; do
  case "$1" in
    --title) TITLE=$2; shift 2 ;;
    -h|--help) sed -n '2,34p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --) shift; break ;;
    *) printf 'bb-pane-run.sh: unexpected argument %s (put the command after --)\n' "$1" >&2; exit 2 ;;
  esac
done
while [ $# -gt 0 ]; do CMD+=( "$1" ); shift; done

REPO=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
if [ ${#CMD[@]} -eq 0 ]; then
  printf 'bb-pane-run.sh: no command given (put it after --)\n' >&2; exit 2
fi
[ -n "$TITLE" ] || TITLE=${CMD[0]}

# The scope. This repo's work happens in a bb thread; fail loudly rather than
# silently creating a pane somewhere the operator is not looking.
if [ -z "${BB_THREAD_ID:-}" ]; then
  printf 'bb-pane-run.sh: BB_THREAD_ID is unset — pass a scope or run inside a bb thread\n' >&2
  exit 2
fi

# Wrappers are kept under the thread's own storage so the operator can read back
# exactly what a pane was asked to run, after the fact.
WRAP_DIR="${BB_THREAD_STORAGE:-$HOME/.bb/thread-storage/$BB_THREAD_ID}/panes"
mkdir -p "$WRAP_DIR" || exit 1
slug=$(printf '%s' "$TITLE" | tr -cs 'A-Za-z0-9._-' '-' | sed 's/^-//; s/-$//')
WRAPPER="$WRAP_DIR/pane-${slug:-command}-$(date +%Y%m%d-%H%M%S).sh"

TITLE_Q=$(printf '%s' "$TITLE" | sed 's/%/%%/g; s/\\/\\\\/g; s/"/\\"/g')

{
  printf '#!/bin/bash\n'
  printf '# Generated by scripts/bb-pane-run.sh — what this pane was asked to run.\n'
  printf 'cd %q || exit 1\n' "$REPO"
  printf 'if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] && [ -r "$HOME/.config/op-sa-token" ]; then\n'
  printf '  export OP_SERVICE_ACCOUNT_TOKEN="$(cat "$HOME/.config/op-sa-token")"\n'
  printf '  echo "[bb-pane] OP_SERVICE_ACCOUNT_TOKEN exported from ~/.config/op-sa-token"\n'
  printf 'fi\n'
  printf 'if [ -z "${SECRETSPEC_REASON:-}" ]; then\n'
  printf '  export SECRETSPEC_REASON="bb terminal pane: %s"\n' "$TITLE_Q"
  printf 'fi\n'
  printf 'echo "[bb-pane] %s"\n' "$TITLE_Q"
  printf 'echo "[bb-pane] cwd %s"\n' "$REPO"
  printf 'date "+[bb-pane] started %%Y-%%m-%%d %%H:%%M:%%S %%Z"\n'
  printf 'echo\n'
  # The command is written as a QUOTED ARRAY, not as `cmd=word word word`.
  # `cmd=./bin/devenv machines deploy netcup` is not a multi-word assignment to
  # bash: it is an assignment prefix on the command `machines`, which does not
  # exist. Measured 2026-09-27: a pane asked to run a multi-word deploy printed
  #   line 15: machines: command not found
  # then `eval "$cmd"` evaluated the empty string and reported exit 0 — a pane
  # that ran NOTHING and looked like it had succeeded. Single-word commands
  # (`./scripts/tailnet-preflight.sh`) hid this, which is why it survived the
  # gate work. `%q` on each element keeps spaces and globs intact.
  printf 'cmd=('; for a in "${CMD[@]}"; do printf ' %q' "$a"; done; printf ' )\n'
  # The display line keeps the quoting too: `${cmd[*]}` alone renders an argument
  # that contains spaces (e.g. an ssh remote command) as if it were several
  # arguments, which makes the record misread as a different command than the
  # one that ran. Measured 2026-09-27 on the post-deploy host check.
  display=$(for a in "${CMD[@]}"; do printf '%q ' "$a"; done)
  printf 'echo "+ %s"\n' "$display"
  printf 'if [ ${#cmd[@]} -eq 0 ]; then echo "[bb-pane] no command to run" >&2; exit 2; fi\n'
  printf 'started=$SECONDS\n'
  printf 'eval "${cmd[@]}"\n'
  printf 'rc=$?\n'
  printf 'echo\n'
  printf 'echo "[bb-pane] exit $rc after $(( SECONDS - started ))s"\n'
  printf 'if [ -t 0 ] && [ -t 1 ]; then echo; echo "-- keeping the pane open; Ctrl-D to close --"; exec bash -i; fi\n'
  printf 'exit "$rc"\n'
} > "$WRAPPER" || exit 1
chmod +x "$WRAPPER"

result=$(bb terminal create --thread "$BB_THREAD_ID" --title "$TITLE" --command "bash $WRAPPER" --json) || exit 1
term_id=$(printf '%s' "$result" | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])') || exit 1

printf '%s\n\n' "$result"
printf 'watch it in the bb app, or read it back:\n'
printf '  bb terminal output %s --json    # chunks are base64; decode them\n' "$term_id"
printf '  bb terminal close  %s\n' "$term_id"
printf 'wrapper: %s\n' "$WRAPPER"
